# Generated by Django 4.1.3 on 2022-11-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DenSys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
    ]
